# Generated by Django 6.0.2 on 2026-02-12 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ("status", "-created_at")},
        ),
    ]
